name: detectorfreesfm
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=1.8.0
  - torchvision=0.9.1
  - cudatoolkit=11.7 # Modify here!
  - tqdm
  - matplotlib
  - pylint
  - conda-forge::h5py=3.1.0
  - conda-forge::loguru=0.5.3
  - conda-forge::scipy
  - conda-forge::ipdb
  - pip
  - pip:
    - -r requirements.txt
